### ISSUE TITLE
Please add a license file, a screen shot, and consider renaming the repository to stigmata

### ISSUE THREAD

**Issue by unixorn** [VLtim43/stigmata.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is too generic. Please consider renaming it to something descriptive, or even just name it stigmata after the plugin file in the repository.

I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Finally, please add a license file, some people won't use any code that doesn't have a license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by VLtim43** [comment]
Hello! I changed the name and added a screenshot and license
